FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    gcc-arm-none-eabi \
    binutils-arm-none-eabi \
    gdb-multiarch \
    make \
    cmake \
    ninja-build \
    git \
    python3 \
    python3-pip \
    openocd \
    stlink-tools \
    usbutils \
    && apt-get clean

WORKDIR /workspace

CMD ["/bin/bash"]
